import {
  Activity,
  Archive,
  AudioLines,
  BrainCircuit,
  Camera,
  ChartNoAxesCombined,
  Cpu,
  CloudOff,
  Code2,
  Database,
  FileText,
  Gauge,
  Github,
  Globe,
  Layers3,
  Linkedin,
  Mail,
  Microchip,
  PackageCheck,
  Radar,
  Rocket,
  ScanLine,
  Server,
  Settings2,
  ShieldCheck,
  Sparkles,
  TerminalSquare,
  UploadCloud,
  Video,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { IconName } from '../data/siteData';

export const iconMap: Record<IconName, LucideIcon> = {
  activity: Activity,
  archive: Archive,
  audio: AudioLines,
  brain: BrainCircuit,
  camera: Camera,
  chart: ChartNoAxesCombined,
  chip: Microchip,
  cloudOff: CloudOff,
  code: Code2,
  cpu: Cpu,
  database: Database,
  file: FileText,
  gauge: Gauge,
  github: Github,
  globe: Globe,
  layers: Layers3,
  linkedin: Linkedin,
  mail: Mail,
  package: PackageCheck,
  radar: Radar,
  rocket: Rocket,
  scan: ScanLine,
  server: Server,
  settings: Settings2,
  shield: ShieldCheck,
  sparkles: Sparkles,
  terminal: TerminalSquare,
  upload: UploadCloud,
  video: Video,
  zap: Zap,
};
